import type { Metadata } from "next";
import { Roboto, } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


const roboto = Roboto({
  variable: "--font-roboto",
  weight:"300",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: {
    default: "Company Profile | Me",
    template: "Company Profile | %s"
  },
  description: "Generated by create next app",
  openGraph: {
    url:"", //contoh isi url itu dari vercel + (vercel/file.svg) -> ukuran gambar memiliki aturan
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
